feat(ui): add more prominent header
ui5-community/bestofui5-website pull request #194
Opened 2022-05-11 10:37 UTC by petermuessig

2022-05-11 10:37 UTC, petermuessig commented
Hi @marianfoo, please take a look...

2022-05-11 10:59 UTC, marianfoo requested changes
i like it!
few things on mobile:
## Button is not visible
![image](https://user-images.githubusercontent.com/13335743/167833865-d06a9fdc-238e-48a6-8773-0a2997129498.png)
## Content in Context Menu not visible
![image](https://user-images.githubusercontent.com/13335743/167834069-1759265d-0bd8-4594-9d90-427eeb8cced2.png)
## minimize header
When on mobile, would be great if the header get smaller, either in general or when scrolling down

2022-05-11 10:59 UTC, marianfoo commented on src/view/App.view.xml
> +            type="Transparent"
```suggestion
            type="Success"
```
i would prefer this to be a action button, clearly visible.
So either this color with `Success` or another color that clearly stands out.

2022-05-11 11:02 UTC, petermuessig commented
I thought about making it more lightweight. Regarding mobile - I think it may be better to fallback to the standard design - at least for the moment. Maybe in future we can get one designer on this topic. 😄

2022-05-11 11:21 UTC, marianfoo commented on src/index.html
> +			}
you mean removing this?
why is it in index.html and not in style.css anyway?

2022-05-11 15:02 UTC, petermuessig commented on src/index.html
> +			}
The splash stuff needs to stay in the index.html to be set early but the rest can be moved into the style.css. I'll have to recheck the mobile case and avoid the usage of the CSS overrides for the mobile scenario.

2022-05-11 15:11 UTC, marianfoo commented on src/index.html
> +			}
yeah, the splash stuff makes sense to stay in index.html
i think you can override it on mobile, just use a different color, that should work

2022-05-11 19:04 UTC, petermuessig commented on src/index.html
> +			}
I disabled the custom header for now on mobile and moved the CSS into the style.css. So we should be good to go.

2022-05-11 19:05 UTC, petermuessig commented on src/index.html
> +			}
Ah, regarding the buttons, I personally prefer to keep them flat. But this is a matter of taste IMO.

2022-05-11 19:23 UTC, marianfoo commented on src/index.html
> +			}
i´m fine with the look on desktop for now

2022-05-11 19:26 UTC, marianfoo commented
as i mentioned before i dont like a prominent header on a content page
it´s different on openui5.org because this is a landing page
nevertheless, it is a nice header and looks way better than before
i reduced the height of the header a bit, are you fine with that?

2022-05-12 07:28 UTC, petermuessig commented
I made some minor tweak about the position of the header and the big header will only be displayed when the screen size is wider than 600px.

2022-05-12 07:38 UTC, marianfoo approved these changes
LGTM!

2022-05-12 07:41 UTC, merged