feat: make header clickable to starting webpage
ui5-community/bestofui5-website pull request #230
Opened 2022-06-14 12:57 UTC by marianfoo

# Changes
replace span inner title with a `html a element`.
Now it´s possible to click on the header to get to the homepage.

2022-06-14 13:05 UTC, marianfoo commented
@petermuessig 
couldn´t think of something better.
I´m replacing the `span` element by the id, which should be stable
there is a fallback anyway if id was not found that cancels the observation

2022-06-15 11:58 UTC, wridgeu commented
What else comes to mind would be using a `customHeader` aggr. for the Page (https://ui5.sap.com/#/api/sap.m.Page%23aggregations) or applying this change at the App Controller level rather than the Component so that you wouldn't have to hardcode the Id but instead get it via `byId` + `getDomRef` smth. like this could maybe work.

Not sure how well though, just some things that I thought about. I like the "workaround" via mutation observer, creative. :)

2022-06-16 16:15 UTC, marianfoo commented
@wridgeu 
You were right.
I even looked at that and was somehow of the opinion that in IBar implementation no link control should be included.
I do not know why.
But it definitely gives a better, more standard solution.
Thanks!
You are welcome to review this.

2022-06-16 21:43 UTC, wridgeu requested changes
I had a look locally and the only thing that I found was some small color mismatch in dark mode (on phone), other than that - lgtm and I'm happy that it helped, it is indeed a more standard way of solving this even though I also liked the observer :P

2022-06-16 21:43 UTC, wridgeu commented on src/css/style.css
> +	color: #1d2d3e;
I think these three `color` adjustments should be put into behind `@media (prefers-color-scheme: light)` (or the other way around :P) because in dark mode (on phone) it looks like this  

![image](https://user-images.githubusercontent.com/14982812/174170310-a457d1a2-ebba-4d0c-ac60-54797fe93e77.png)

Without this adjustment, using the default, it's fine I'd say 

![image](https://user-images.githubusercontent.com/14982812/174170390-6517691b-981f-41fd-8648-d3d466a9e2a3.png)

I also found out that the dynamic prefers-color-scheme switch in dev tools seems to be generally available now in chrome, pretty cool & might help :)

![image](https://user-images.githubusercontent.com/14982812/174170640-b5969482-84ff-440a-9742-80393e675210.png)

2022-06-17 06:02 UTC, marianfoo commented on src/css/style.css
> +	color: #1d2d3e;
Yep, I thought about that too and deliberately didn't match the InfoLabel or theme.
If you were to separate the colors, which one would you want to use?
Using the theme switch for a few month and yes it is very helpful :)

2022-06-17 08:04 UTC, wridgeu commented on src/css/style.css
> +	color: #1d2d3e;
I don't think we need another color when the current ones are put behind a media query as the default looks alright I guess, it also matches with the tab headers 

![image](https://user-images.githubusercontent.com/14982812/174254816-43760c70-3c8a-4569-9fd6-6e649ef7ee66.png)
![image](https://user-images.githubusercontent.com/14982812/174254849-f1ae2ed7-1e79-4124-9876-8bcccc4063e2.png)

2022-06-17 08:35 UTC, marianfoo commented on src/css/style.css
> +	color: #1d2d3e;
Added dark/light css
Do you have an idea how to avoid this duplications?
Not that familiar with CSS

2022-06-17 08:42 UTC, wridgeu commented on src/css/style.css
> +	color: #1d2d3e;
I'm not a CSS hero either but what I'd do without a some sort of pre-processor is something like this

```css
.headerLink.sapMLnk:link {
  text-shadow: none;
  font-weight: bold;
  font-size: inherit;
  /* remove link styles */
  text-decoration: none;
  outline: none;
}
.headerLink.sapMLnk:visited {
  text-shadow: none;
  font-weight: bold;
  font-size: inherit;
  /* remove link styles */
  text-decoration: none;
  outline: none;
}
.headerLink.sapMLnk {
  text-shadow: none;
  font-weight: bold;
  font-size: inherit;
  /* remove link styles */
  text-decoration: none;
  outline: none;
}

@media (prefers-color-scheme: dark) {
	.headerLink.sapMLnk:link {
		color: white;
	}
	.headerLink.sapMLnk:visited {
		color: white;
	}
	.headerLink.sapMLnk {
		color: white;
	}
}

@media (prefers-color-scheme: light) {
	.headerLink.sapMLnk:link {
		color: #1d2d3e;
	}
	.headerLink.sapMLnk:visited {
		color: #1d2d3e;
	}
	.headerLink.sapMLnk {
		color: #1d2d3e;
	}
}
```

2022-06-17 08:46 UTC, marianfoo commented on src/css/style.css
> +	color: #1d2d3e;
better than mine, thanks :)

2022-06-17 08:47 UTC, wridgeu commented on src/css/style.css
> +	color: #1d2d3e;
lgtm :)

2022-06-17 08:47 UTC, wridgeu approved these changes

2022-06-17 08:50 UTC, merged