feat: replace select dialog with webc viewsettingsdialog
ui5-community/bestofui5-website pull request #247
Opened 2022-06-21 10:57 UTC by marianfoo

2022-06-21 11:00 UTC, marianfoo commented
current error:
![image](https://user-images.githubusercontent.com/13335743/174783771-1e1c95fd-1891-45e3-a113-d81f7fc1f3e0.png)
here:
https://github.com/ui5-community/bestofui5-website/pull/247/files#diff-009457ff331a1df27a38d8bbd6d062c2591322cd726314ebe11cbda5f68b9ed8R71-R81

@petermuessig can you might help here?
using the [ViewSettingsDialog](https://sap.github.io/ui5-webcomponents/playground/components/ViewSettingsDialog/) from the OpenUI5 Web Components
It does not work in a fragment

2022-06-26 13:54 UTC, marianfoo commented
Hey @wridgeu ,
would be great to have your feedback on this.
Anytime when it works best for you.
Cheers

2022-06-26 19:11 UTC, wridgeu requested changes
Hey @marianfoo, sure thing, thanks for asking :)  

## icons/design
I feel like the icons are a bit too large which make them feel out of place. For the visuals on the two filter drop downs I made some changes locally regarding the sizing, color, flexbox basesize on phone and some margin changes:
```xml
<FlexBox alignItems="Center" wrap="{= ${device>/system/phone} === true ? 'Wrap' : 'NoWrap' }">
  <HBox alignItems="Center">
    <core:Icon src="sap-icon://sort" class="{= ${device>/system/phone} === true ? sapUiTinyMarginBeginEnd : sapUiTinyMarginEnd }"/>
    <Select width="100%" id="selectSort" forceSelection="true" change=".onSortSelectChange" selectedKey="{settings>/selectKey}">
             ...
    </Select>
    <layoutData>
      <FlexItemData growFactor="1" baseSize="{= ${device>/system/phone} === true ? '100%' : '0' }" />
    </layoutData>
  </HBox>
  <HBox alignItems="Center">
    <core:Icon src="sap-icon://filter" class="sapUiTinyMarginBeginEnd" />
    <MultiComboBox>
               ....
    </MultiComboBox>
    <layoutData>
      <FlexItemData growFactor="1" baseSize="{= ${device>/system/phone} === true ? '100%' : '0' }" />
    </layoutData>
  </HBox>
</FlexBox>
```

Let me know what you think, it comes out like this:

phone dark
![image](https://user-images.githubusercontent.com/14982812/175829247-ada4f8fb-bed0-479e-b483-79dfdfa961b9.png)

phone light
![image](https://user-images.githubusercontent.com/14982812/175829311-04717575-6690-48c0-867e-e371d6d11b8c.png)

desktop dark
![image](https://user-images.githubusercontent.com/14982812/175829274-203c0389-a2e4-46bc-856d-ef1b39ea14bc.png)

desktop light
![image](https://user-images.githubusercontent.com/14982812/175829298-99999606-69aa-47bb-96d1-88fd277978c4.png)

## xml namespaces/imports

according to my IDE `webc` and `ui5cc` aren't used within `AllPackages.view.xml`, I put another comment related to this in the "review" ^^
![image](https://user-images.githubusercontent.com/14982812/175829447-459207c7-b648-4432-b082-6cd7babb8734.png)

I didn't check all the implementation details too thoroughly but I clicked around a bit and it works.  :P  

In some cases, like here (following LoC) I feel like you could disable the [eslint warning](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/unbound-method.md) for this line but I  guess that is personal preference. https://github.com/ui5-community/bestofui5-website/blob/f61d6b524fba672bc8fa5ba512456b8b20ff92d4/src/controller/AllPackages.controller.ts#L19 

Hope this helps a bit. :)

2022-06-26 19:11 UTC, wridgeu commented on src/manifest.json
> +        "sap.ui.webc.main": {},
Is `webc.main` used? I ran a few searches but could only find namespace usages that were shown as "unused" for me. Maybe I overlooked something. If it isn't used, this could be removed in manifest, yaml and the respective views.

2022-06-26 19:11 UTC, wridgeu commented on src/test/e2e/search.test.js
> +		expect(listItems.length).toEqual(2);
I'm not that much of a testing hero (i have tons to catch up 😅) but wouldn't it make more sense to have some mocking here? This result would otherwhise always change and therefore the test always needs to be adjusted when the used data changes, even though the functionality might stay the same.

2022-06-26 19:50 UTC, marianfoo commented on src/manifest.json
> +        "sap.ui.webc.main": {},
was tryin out viewsettingsdialog, changed it to multicombobox, that´s why webc is there
can be removed

2022-06-26 19:52 UTC, marianfoo commented on src/test/e2e/search.test.js
> +		expect(listItems.length).toEqual(2);
yeah, you´re right, i was hoping with the search value there will be alway just one result
will create a issue for it

2022-06-26 19:53 UTC, marianfoo commented
> I feel like the icons are a bit too large which make them feel out of place. For the visuals on the two filter drop downs I made some changes locally regarding the sizing, color, flexbox basesize on phone and some margin changes

Perfect, wanted to achive that but i was tryin to get some results :)
Can you commit that please

2022-06-26 19:58 UTC, wridgeu commented
> Perfect, wanted to achive that but i was tryin to get some results :) Can you commit that please

Done :)

2022-06-26 20:43 UTC, marianfoo commented
Looking good, thanks for your feedback :)

2022-06-26 20:44 UTC, merged